dev:
  MY_NAME: >-
    encrypted:AQICAHgGFLl2N1SuVXH3TazAj87U3URW7wYy2h8mv2BUSpemOQESdd7Fx/cPzDfE/UilrV2VAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1OSUkWQ9/G3bpOk+AgEQgCJgNacEeu6V4nxMHq6c/LnEnU2x7uD5xUTgSxy4hQnCVAjg
prod:
  MY_NAME: >-
    encrypted:AQICAHgGFLl2N1SuVXH3TazAj87U3URW7wYy2h8mv2BUSpemOQG7nfk1J8DBRaTiN9eYdrhBAAAAaTBnBgkqhkiG9w0BBwagWjBYAgEAMFMGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM1cjdJwORyhdq5SP6AgEQgCbpsqh0NxX3lF38ZQ6Zj9wol1cFI56tLc61pk8P60dJ35cVIJ5rqg==
  TTT: >-
    encrypted:AQICAHgGFLl2N1SuVXH3TazAj87U3URW7wYy2h8mv2BUSpemOQENO97Ht5gSKrLqPl2Seh9FAAAAYTBfBgkqhkiG9w0BBwagUjBQAgEAMEsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzg33ccz1xOjCh+1aAgEQgB64KC8TDr/8D+s+1i08+Seeu6SfS1ZkVaX1M2y+Nbc=
