service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-env-generator

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-2

app: myapp-dev
tenant: lorenzoflyvictor
frameworkVersion: "=1.30.0"

custom:
  envFiles:
    - environment.yml
  envEncryptionKeyId:
    dev: "2c0df623-67c8-4b39-a643-aa8d60d1e0ec"
    prod: "2c0df623-67c8-4b39-a643-aa8d60d1e0ec"

functions:
  hello:
    handler: src/handlers/handler.hello
    events:
      - http:
          path: hello
          method: get